### ISSUE TITLE
neededConcepts are not properly shown in unitEdit

### ISSUE THREAD

**Issue by joaobarcia** [joaobarcia/Pointsquare#24]
Seems there is an error related with getNeeds method:
```
I20180523-17:02:12.554(2)? Exception while invoking method 'getNeeds' { stack: 'TypeError: Cannot read property \'needs\' of undefined\n    at Object.getNeeds (lib/globalFunctions/globalFunctions.js:327:27)\n    at get_needs (server/methods/methods2.js:1017:33)\n    at MethodInvocation.getNeeds (server/methods/methods2.js:1715:12)\n    at MethodInvocation.methodMap.(anonymous function) (packages/meteorhacks_kadira.js:2731:30)\n    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)\n    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)\n    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)\n    at Promise (packages/ddp-server/livedata_server.js:715:46)\n    at new Promise (<anonymous>)\n    at Session.method (packages/ddp-server/livedata_server.js:689:23)\n    at packages/meteorhacks_kadira.js:2619:38\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)\n    at Session.sessionProto.protocol_handlers.method (packages/meteorhacks_kadira.js:2618:44)\n    at packages/ddp-server/livedata_server.js:559:43',
I20180523-17:02:12.554(2)?   source: 'method' }
I20180523-17:03:07.076(2)? Exception while invoking method 'editLanguage' { stack: 'TypeError: Cannot read property \'needs\' of undefined\n    at Object.getNeeds (lib/globalFunctions/globalFunctions.js:327:27)\n    at get_needs (server/methods/methods2.js:1017:33)\n    at change_language_requisite (server/methods/methods2.js:837:22)\n    at MethodInvocation.editLanguage (server/methods/methods2.js:1662:12)\n    at MethodInvocation.methodMap.(anonymous function) (packages/meteorhacks_kadira.js:2731:30)\n    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)\n    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)\n    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)\n    at Promise (packages/ddp-server/livedata_server.js:715:46)\n    at new Promise (<anonymous>)\n    at Session.method (packages/ddp-server/livedata_server.js:689:23)\n    at packages/meteorhacks_kadira.js:2619:38\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)\n    at Session.sessionProto.protocol_handlers.method (packages/meteorhacks_kadira.js:2618:44)\n    at packages/ddp-server/livedata_server.js:559:43',
I20180523-17:03:07.077(2)?   source: 'method' }
I20180523-17:03:07.143(2)? Exception while invoking method 'getNeeds' { stack: 'TypeError: Cannot read property \'needs\' of undefined\n    at Object.getNeeds (lib/globalFunctions/globalFunctions.js:327:27)\n    at get_needs (server/methods/methods2.js:1017:33)\n    at MethodInvocation.getNeeds (server/methods/methods2.js:1715:12)\n    at MethodInvocation.methodMap.(anonymous function) (packages/meteorhacks_kadira.js:2731:30)\n    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)\n    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)\n    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)\n    at Promise (packages/ddp-server/livedata_server.js:715:46)\n    at new Promise (<anonymous>)\n    at Session.method (packages/ddp-server/livedata_server.js:689:23)\n    at packages/meteorhacks_kadira.js:2619:38\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)\n    at Session.sessionProto.protocol_handlers.method (packages/meteorhacks_kadira.js:2618:44)\n    at packages/ddp-server/livedata_server.js:559:43',
I20180523-17:03:07.144(2)?   source: 'method' }
```

**Comment by joaobarcia** [comment]
Closing as this seems to have been solved. Can be re-opened in case it is necessary
